version: "3"

services:
  gateway-service:
    build:
      context: services/gateway
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/home/node

  posts-service:
    build:
      context: services/posts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/posts:/home/node
    environment:
      DATABASE_NAME: &postsDatabaseName posts
      DATABASE_USER: &postsDatabaseUser posts
      DATABASE_PASSWORD: &postsDatabasePassword posts

  posts-database:
    build:
      context: services/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: *postsDatabaseName
      POSTGRES_USER: *postsDatabaseUser
      POSTGRES_PASSWORD: *postsDatabasePassword
