version: "3"

services:
  gateway-service:
    image: aminnairi/gateway-service:0.1.0
    ports:
      - 3000:3000

  posts-service:
    image: aminnairi/posts-service:0.1.0

  posts-database:
    image: aminnairi/posts-database:0.1.0
