version: "3"

services:
  gateway-service:
    image: aminnairi/gateway-service:0.1.0
    build:
      context: services/gateway
      dockerfile: Dockerfile
      target: production

  posts-service:
    image: aminnairi/posts-service:0.1.0
    build:
      context: services/posts
      dockerfile: Dockerfile
      target: production

  posts-database:
    image: aminnairi/posts-database:0.1.0
    build:
      context: services/database
      dockerfile: Dockerfile
